### ISSUE TITLE
Sessions are showing as "at Location TBD" for the location

### ISSUE THREAD

**Issue by fetching** [SwiftFest/android-app#20]
All sessions are showing a location of "at Location TBD" right now. I'm guessing that the "room" field is not set at the back end?

See screenshot in this ticket for what is seen in the app:
https://github.com/SwiftFest/android-app/issues/19

And here is the data in the debugger showing room="Location TBD"
<img width="764" alt="Screen Shot 2019-07-20 at 1 14 32 PM" src="https://user-images.githubusercontent.com/15278837/61581771-6f701480-aaf0-11e9-9640-3139f1f4c9cf.png">

**Comment by GiorgioNatili** [comment]
Content issue, fixed.
