### ISSUE TITLE
Agenda displays only first name of speakers, no last name and no company

### ISSUE THREAD

**Issue by fetching** [SwiftFest/android-app#21]
From Dee:

The top-level list of speakers in the Agenda contains speaker photos and first name along with the talk title. However, the speaker's last name is not being displayed.

We should display the last name as well.  Here is a screenshot of what is seen in the app right now:
<img width="314" alt="Screen Shot 2019-07-20 at 2 50 21 PM" src="https://user-images.githubusercontent.com/15278837/61582865-18713c00-aafe-11e9-97d3-0173261079ac.png">

**Comment by GiorgioNatili** [comment]
Ready for QA https://github.com/SwiftFest/android-app/pull/26.

**Comment by fetching** [comment]
Merged to master and looks good.
