### ISSUE TITLE
Giorgio's talk still shows at TBD for location

### ISSUE THREAD

**Issue by fetching** [SwiftFest/android-app#27]
Giorgio's talk is still showing TBD for the Location. Does it need an update at the web site back end?
<img width="306" alt="Screen Shot 2019-07-24 at 8 35 44 AM" src="https://user-images.githubusercontent.com/15278837/61793986-35538b00-adee-11e9-979e-25c5b4bfaab5.png">

**Comment by GiorgioNatili** [comment]
Fixed, data issue.
